StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{55EECB5B4A37DCF9}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Full_Name"
   Target_en_us "Rugged Desk (Full)"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1441713716
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{B195E67D19D4DB1E}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Full.et"
  }
  CustomStringTableItem "{55EECB5B4A368209}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Name"
   Target_en_us "Rugged Desk"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1441713868
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{EB8E1C0909C73A70}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01.et"
  }
 }
}