StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5A04791140C1AC7D}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Black_Full_Name"
   Target_en_us "Black Rugged Desk - Full"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{921D7E4B53C9896A}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Black_Full.et"
  }
  CustomStringTableItem "{5A04791140C12FD5}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Black_Lid_Name"
   Target_en_us "Black Rugged Desk Lid"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{63BF30B0A82BCC4B}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Black_Lid.et"
  }
  CustomStringTableItem "{5A04791140C0715D}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Black_Name"
   Target_en_us "Black Rugged Desk"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{B32E6D575E73A9C0}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Black.et"
  }
  CustomStringTableItem "{5A04791140CE98DF}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Black_Wing_Name"
   Target_en_us "Black Rugged Desk Wing"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{B75D3E10451E7500}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Black_Wing.et"
  }
  CustomStringTableItem "{55EECB5B4A37DCF9}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Full_Name"
   Target_en_us "Rugged Desk (Full)"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1441713716
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{B195E67D19D4DB1E}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Full.et"
  }
  CustomStringTableItem "{55EECB5B4A368209}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Name"
   Target_en_us "Rugged Desk"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1441713868
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{EB8E1C0909C73A70}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01.et"
  }
  CustomStringTableItem "{5A04791140CF60A9}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Olive_Full_Name"
   Target_en_us "Olive Rugged Desk - Full"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{ED86F664B773C698}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Olive_Full.et"
  }
  CustomStringTableItem "{5A04791140CC83AC}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Olive_Lid_Name"
   Target_en_us "Olive Rugged Desk Lid"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{6E590E73A3745B07}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Olive_Lid.et"
  }
  CustomStringTableItem "{5A04791140CE28F0}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Olive_Name"
   Target_en_us "Olive Rugged Desk"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{D0804E0B079126E3}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Olive.et"
  }
  CustomStringTableItem "{5A04791140CC12AC}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Olive_Wing_Name"
   Target_en_us "Olive Rugged Desk Wing"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{C8C6B63FA1A43AF2}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Olive_Wing.et"
  }
  CustomStringTableItem "{5A04791140CAC95D}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Sand_Full_Name"
   Target_en_us "Sand Rugged Desk - Full"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{8DE49070BFA84DC2}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Sand_Full.et"
  }
  CustomStringTableItem "{5A04791140CA1C91}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Sand_Lid_Name"
   Target_en_us "Sand Rugged Desk Lid"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{7D98404F74165F52}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Sand_Lid.et"
  }
  CustomStringTableItem "{5A04791140CDA20D}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Sand_Name"
   Target_en_us "Sand Rugged Desk"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{0EC28A3406370B15}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Sand.et"
  }
  CustomStringTableItem "{5A04791140CBAE1D}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Sand_Wing_Name"
   Target_en_us "Sand Rugged Desk Wing"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1510242872
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{A8A4D02BA97FB1A8}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Sand_Wing.et"
  }
 }
}