StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5605132A711F423D}" {
   Id "SampleMod-EditableEntity_SampleCar_01_Name"
   Target_en_us "Sample New Car (Black)"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1443173495
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{1398A24AB596FFE1}Prefabs/Vehicles/Wheeled/SampleCar_01/SampleCar_01.et"
  }
  CustomStringTableItem "{5605132A711DBA12}" {
   Id "SampleMod-EditableEntity_SampleCar_01_white_Name"
   Target_en_us "Sample New Car (White)"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1443173495
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{EA4402E038B96F6C}Prefabs/Vehicles/Wheeled/SampleCar_01/SampleCar_01_white.et"
  }
 }
}