StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{55E10790E622FC1E}" {
   Id "SampleMod-EditableEntity_UAZ469_Modded_Name"
   Target_en_us "UAZ-469 (Modded)"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1440810977
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{602B59AB3DF39462}Prefabs/Vehicles/Wheeled/UAZ469_Modded.et"
  }
 }
}