StringTable {
 Items {
  CustomStringTableItem "{55E092E7E7884D0D}" {
   Id "AR-EditableEntity_PortableDesk_01_Full_Name"
   Target_en_us "(PortableDesk_01_Full)"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1440781109
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{B195E67D19D4DB1E}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Full.et"
  }
  CustomStringTableItem "{55E092E7E79711BC}" {
   Id "AR-EditableEntity_PortableDesk_01_Name"
   Target_en_us "(PortableDesk_01)"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1440781109
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{EB8E1C0909C73A70}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01.et"
  }
  CustomStringTableItem "{55E0A218B3AEBBDB}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Full_Name"
   Target_en_us "(PortableDesk_01_Full)"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1440785133
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{B195E67D19D4DB1E}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01_Full.et"
  }
  CustomStringTableItem "{55E0A218B3AD862E}" {
   Id "SampleMod-EditableEntity_PortableDesk_01_Name"
   Target_en_us "(PortableDesk_01)"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1440785133
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    300
   }
   SourceFile "{EB8E1C0909C73A70}PrefabsEditable/Auto/Props/Military/Camps/E_PortableDesk_01.et"
  }
 }
}