StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{55E0EB47ED09B6F0}" {
   Id "SampleMod-Magazine_Magazine_AK74_30rnd_Modded_Name"
   Target_en_us "7L10"
   Modified 1440803724
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    1100
   }
   SourceFile "{A4317E2621586AE3}Prefabs/Weapons/Magazines/Magazine_AK74_30rnd_Modded.et"
  }
  CustomStringTableItem "{55E0EB47ED0A8220}" {
   Id "SampleMod-Uniform_Rifle_AK74_Modded_Name"
   Target_en_us "AK-74 (Camo)"
   Modified 1440803724
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{3C399F23FE9B2E7F}Prefabs/Weapons/Rifles/Rifle_AK74_Modded.et"
  }
 }
}