StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5AF89E61750D5833}" {
   Id "SampleMod-Magazine_65x39C_SampleWeapon_01_30rnd_Base_Description"
   Target_en_us "Magazine loaded with 6.5x39mm NATO rounds"
   Modified 1526243433
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{8483C43851C6C0C4}Prefabs/Magazines/Magazine_65x39C_SampleWeapon_01_30rnd_Base.et"
  }
  CustomStringTableItem "{5AF89E61750D481C}" {
   Id "SampleMod-Magazine_65x39C_SampleWeapon_01_30rnd_Base_Name"
   Target_en_us "6.5x39mm 30rnd STANAG Mag"
   Modified 1526243433
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{8483C43851C6C0C4}Prefabs/Magazines/Magazine_65x39C_SampleWeapon_01_30rnd_Base.et"
  }
  CustomStringTableItem "{5AF89E616243E192}" {
   Id "SampleMod-Optic_SampleOptic_01_Description"
   Target_en_us "Optic with 4x magnification designed to be used together with Sample Weapon"
   Modified 1526243407
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{63DDF1EFECD7F988}Prefabs/Attachments/Optics/Optic_SampleOptic_01.et"
  }
  CustomStringTableItem "{5AF89E616243D02F}" {
   Id "SampleMod-Optic_SampleOptic_01_Name"
   Target_en_us "Sample Carryhandle Optic"
   Modified 1526243407
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{63DDF1EFECD7F988}Prefabs/Attachments/Optics/Optic_SampleOptic_01.et"
  }
 }
}