StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5D0CCB25620357D0}" {
   Id "SampleMod-EditableEntity_AmmoBox_SampleWeaponMagazines_Name"
   Target_en_us "Sample New Weapon Ammo Crate"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1561120984
   Author "phammac"
   LastChanged "phammac"
   Labels {
    300
   }
   SourceFile "{A7B20DD168C5ACF5}PrefabsEditable/Auto/Props/Military/AmmoBoxes/E_AmmoBox_SampleWeaponMagazines.et"
  }
  CustomStringTableItem "{5D0CCB25481B944A}" {
   Id "SampleMod-EditableEntity_ArsenalBox_SampleNewWeapon_Name"
   Target_en_us "Sample New Weapon Arsenal Box"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1561121025
   Author "phammac"
   LastChanged "phammac"
   Labels {
    300
   }
   SourceFile "{5E540AA4741A9B74}PrefabsEditable/Auto/Systems/Arsenal/ArsenalBoxes/USSR/E_ArsenalBox_SampleNewWeapon.et"
  }
  CustomStringTableItem "{5D0CCB256202353B}" {
   Id "SampleMod-EditableEntity_EquipmentBoxWodden_SampleWeapon_Name"
   Target_en_us "Sample New Weapon Crate"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1561120984
   Author "phammac"
   LastChanged "phammac"
   Labels {
    300
   }
   SourceFile "{EEA866D6E77051C8}PrefabsEditable/Auto/Props/Military/AmmoBoxes/US/E_EquipmentBoxWodden_SampleWeapon.et"
  }
  CustomStringTableItem "{5AF89E61750D5833}" {
   Id "SampleMod-Magazine_65x39C_SampleWeapon_01_30rnd_Base_Description"
   Target_en_us "Magazine loaded with 6.5x39mm NATO rounds"
   Modified 1526243433
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{8483C43851C6C0C4}Prefabs/Weapons/Magazines/Magazine_65x39C_SampleWeapon_01_30rnd_Base.et"
  }
  CustomStringTableItem "{5AF89E61750D481C}" {
   Id "SampleMod-Magazine_65x39C_SampleWeapon_01_30rnd_Base_Name"
   Target_en_us "6.5x39mm 30rnd STANAG Mag"
   Modified 1526243433
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{8483C43851C6C0C4}Prefabs/Weapons/Magazines/Magazine_65x39C_SampleWeapon_01_30rnd_Base.et"
  }
  CustomStringTableItem "{5CEE80DD027947A7}" {
   Id "SampleMod-Magazine_65x39C_SampleWeapon_01_30rnd_LastTracer_Description"
   Target_en_us "Magazine loaded with 6.5x39mm NATO cartridges atop several tracer rounds"
   Modified 1559134936
   Author "phammac"
   LastChanged "phammac"
  }
  CustomStringTableItem "{5CEE80DDAF0E3CA7}" {
   Id "SampleMod-Magazine_65x39C_SampleWeapon_01_30rnd_Tracer_Description"
   Target_en_us "Magazine loaded with 6.5x39mm NATO tracer rounds"
   Modified 1559134788
   Author "phammac"
   LastChanged "phammac"
  }
  CustomStringTableItem "{5CEE80DDBEA3F48D}" {
   Id "SampleMod-Magazine_65x39C_SampleWeapon_01_30rnd_Tracer_Name"
   Target_en_us "6.5x39mm 30rnd STANAG Tracer Mag"
   Modified 1559134560
   Author "phammac"
   LastChanged "phammac"
  }
  CustomStringTableItem "{5D1AAB63A0F65921}" {
   Id "SampleMod-Optic_SampleCollimator_01_Description"
   Target_en_us "Small 1x collimator sight"
   Modified 1562029024
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{C84595BF6F321B09}Prefabs/Weapons/Attachments/Optics/Optic_SampleCollimator_01.et"
  }
  CustomStringTableItem "{5D1AAB63A0F6B656}" {
   Id "SampleMod-Optic_SampleCollimator_01_Name"
   Target_en_us "Sample Collimator"
   Modified 1562029024
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{C84595BF6F321B09}Prefabs/Weapons/Attachments/Optics/Optic_SampleCollimator_01.et"
  }
  CustomStringTableItem "{5CEEA1EABCF30DFB}" {
   Id "SampleMod-Optic_SampleIronsight_01_Base_Name"
   Target_en_us "Ironsight"
   Modified 1559143008
   Author "phammac"
   LastChanged "phammac"
   Labels {
    0 1200
   }
   SourceFile "{2CF89ADA36CC318B}Prefabs/Weapons/Attachments/Optics/Optic_SampleIronsight_01_Base.et"
  }
  CustomStringTableItem "{5CEEA1EABCF01F3F}" {
   Id "SampleMod-Optic_SampleIronsight_01_Front_Name"
   Target_en_us "Ironsight Front"
   Modified 1559143008
   Author "phammac"
   LastChanged "phammac"
   Labels {
    0 1200
   }
   SourceFile "{5C3C9FE480E417D7}Prefabs/Weapons/Attachments/Optics/Optic_SampleIronsight_01_Front.et"
  }
  CustomStringTableItem "{5CEEA1EABCF1169D}" {
   Id "SampleMod-Optic_SampleIronsight_01_Rear_Name"
   Target_en_us "Ironsight Rear"
   Modified 1559143008
   Author "phammac"
   LastChanged "phammac"
   Labels {
    0 1200
   }
   SourceFile "{4842D1F1D47C9CD7}Prefabs/Weapons/Attachments/Optics/Optic_SampleIronsight_01_Rear.et"
  }
  CustomStringTableItem "{5AF89E616243E192}" {
   Id "SampleMod-Optic_SampleOptic_01_Description"
   Target_en_us "Optic with 4x magnification designed to be used together with Sample Weapon"
   Modified 1526243407
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{63DDF1EFECD7F988}Prefabs/Weapons/Attachments/Optics/Optic_SampleOptic_01.et"
  }
  CustomStringTableItem "{5AF89E616243D02F}" {
   Id "SampleMod-Optic_SampleOptic_01_Name"
   Target_en_us "Sample Carryhandle Optic"
   Modified 1526243407
   Author "reyhard"
   LastChanged "reyhard"
   Labels {
    0 1200
   }
   SourceFile "{63DDF1EFECD7F988}Prefabs/Weapons/Attachments/Optics/Optic_SampleOptic_01.et"
  }
 }
}